# Generated by Django 2.0.9 on 2018-11-06 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0002_tournament'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
