# Generated by Django 2.0.9 on 2018-11-06 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0003_delete_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=2018)),
                ('game', models.CharField(max_length=10)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball.Team')),
            ],
        ),
    ]
