# Generated by Django 2.0.9 on 2018-11-07 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0004_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='winner',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
