# Generated by Django 2.0.9 on 2018-11-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0006_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='venue_name',
            field=models.CharField(max_length=60),
        ),
    ]
