# Generated by Django 2.0.9 on 2018-11-14 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0014_auto_20181108_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['school_name']},
        ),
    ]
