# Generated by Django 2.0.9 on 2018-11-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0017_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='bottom_left_region',
            field=models.CharField(choices=[('EAST', 'East'), ('MIDWEST', 'Midwest'), ('SOUTH', 'South'), ('WEST', 'West')], default='EAST', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='bottom_right_region',
            field=models.CharField(choices=[('EAST', 'East'), ('MIDWEST', 'Midwest'), ('SOUTH', 'South'), ('WEST', 'West')], default='WEST', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='top_left_region',
            field=models.CharField(choices=[('EAST', 'East'), ('MIDWEST', 'Midwest'), ('SOUTH', 'South'), ('WEST', 'West')], default='MIDWEST', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='top_right_region',
            field=models.CharField(choices=[('EAST', 'East'), ('MIDWEST', 'Midwest'), ('SOUTH', 'South'), ('WEST', 'West')], default='SOUTH', max_length=7),
            preserve_default=False,
        ),
    ]
