# Generated by Django 2.0.9 on 2018-11-20 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0020_auto_20181120_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('elo', models.PositiveSmallIntegerField()),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball.Team')),
            ],
        ),
    ]
