# Generated by Django 2.0.9 on 2018-11-20 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0021_season_stats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season_stats',
            old_name='team_id',
            new_name='team',
        ),
    ]
