# Generated by Django 2.0.9 on 2018-11-28 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0027_auto_20181124_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season_stats',
            name='team',
        ),
        migrations.DeleteModel(
            name='Season_stats',
        ),
    ]
