# Generated by Django 2.0.9 on 2018-11-28 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0028_auto_20181128_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('elo', models.PositiveSmallIntegerField()),
                ('made_tournament', models.BooleanField()),
                ('tournament_seed', models.PositiveSmallIntegerField()),
                ('tournament_region', models.CharField(choices=[('EAST', 'East'), ('MIDWEST', 'Midwest'), ('SOUTH', 'South'), ('SOUTHEAST', 'Southeast'), ('SOUTHWEST', 'Southwest'), ('WEST', 'West')], max_length=10)),
                ('tournament_result', models.CharField(max_length=60)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball.Team')),
            ],
        ),
    ]
