# Generated by Django 2.0.9 on 2018-12-05 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0029_season_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season_stats',
            name='team',
        ),
        migrations.DeleteModel(
            name='Season_stats',
        ),
    ]
