# Generated by Django 2.0.9 on 2018-12-05 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0030_auto_20181205_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('elo', models.PositiveSmallIntegerField()),
                ('ppg', models.DecimalField(decimal_places=1, max_digits=4)),
                ('ppga', models.DecimalField(decimal_places=1, max_digits=4)),
                ('made_tournament', models.BooleanField()),
                ('tournament_seed', models.PositiveSmallIntegerField()),
                ('tournament_region', models.CharField(choices=[('EAST', 'East'), ('MIDWEST', 'Midwest'), ('SOUTH', 'South'), ('SOUTHEAST', 'Southeast'), ('SOUTHWEST', 'Southwest'), ('WEST', 'West')], max_length=10)),
                ('tournament_wins', models.PositiveSmallIntegerField()),
                ('tournament_losses', models.PositiveSmallIntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball.Team')),
                ('tournament_lost_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_to', to='basketball.Team')),
            ],
        ),
    ]
