# Generated by Django 2.0.9 on 2018-12-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0031_season_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='season_stats',
            name='losses',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season_stats',
            name='wins',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
