# Generated by Django 2.0.9 on 2018-12-08 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0032_auto_20181205_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season_stats',
            name='tournament_lost_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lost_to', to='basketball.Team'),
        ),
    ]
