# Generated by Django 2.0.9 on 2018-12-13 22:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0034_auto_20181207_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='school_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='venue_capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
