# Generated by Django 2.0.9 on 2018-12-13 23:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0035_auto_20181213_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='bottom_left_ee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_ee_id', to='basketball.Team', verbose_name='Bottom Left Elite Eight Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_left_r1_g1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_r1_g1_id', to='basketball.Team', verbose_name='Bottom Left Round 1 Game 1 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_left_r1_g2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_r1_g2_id', to='basketball.Team', verbose_name='Bottom Left Round 1 Game 2 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_left_r1_g3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_r1_g3_id', to='basketball.Team', verbose_name='Bottom Left Round 1 Game 3 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_left_r1_g4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_r1_g4_id', to='basketball.Team', verbose_name='Bottom Left Round 1 Game 4 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_left_r1_g5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_r1_g5_id', to='basketball.Team', verbose_name='Bottom Left Round 1 Game 5 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_left_r1_g6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_r1_g6_id', to='basketball.Team', verbose_name='Bottom Left Round 1 Game 6 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_left_r1_g7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_r1_g7_id', to='basketball.Team', verbose_name='Bottom Left Round 1 Game 7 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_left_r1_g8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_r1_g8_id', to='basketball.Team', verbose_name='Bottom Left Round 1 Game 8 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_left_r2_g1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_r2_g1_id', to='basketball.Team', verbose_name='Bottom Left Round 2 Game 1 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_left_r2_g2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_r2_g2_id', to='basketball.Team', verbose_name='Bottom Left Round 2 Game 2 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_left_r2_g3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_r2_g3_id', to='basketball.Team', verbose_name='Bottom Left Round 2 Game 3 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_left_r2_g4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_r2_g4_id', to='basketball.Team', verbose_name='Bottom Left Round 2 Game 4 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_left_ss_g1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_ss_g1_id', to='basketball.Team', verbose_name='Bottom Left Sweet 16 Game 1 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_left_ss_g2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_ss_g2_id', to='basketball.Team', verbose_name='Bottom Left Sweet 16 Game 2 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_right_ee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_ee_id', to='basketball.Team', verbose_name='Bottom Right Elite Eight Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_right_r1_g1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_r1_g1_id', to='basketball.Team', verbose_name='Bottom Right Round 1 Game 1 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_right_r1_g2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_r1_g2_id', to='basketball.Team', verbose_name='Bottom Right Round 1 Game 2 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_right_r1_g3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_r1_g3_id', to='basketball.Team', verbose_name='Bottom Right Round 1 Game 3 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_right_r1_g4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_r1_g4_id', to='basketball.Team', verbose_name='Bottom Right Round 1 Game 4 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_right_r1_g5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_r1_g5_id', to='basketball.Team', verbose_name='Bottom Right Round 1 Game 5 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_right_r1_g6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_r1_g6_id', to='basketball.Team', verbose_name='Bottom Right Round 1 Game 6 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_right_r1_g7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_r1_g7_id', to='basketball.Team', verbose_name='Bottom Right Round 1 Game 7 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_right_r1_g8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_r1_g8_id', to='basketball.Team', verbose_name='Bottom Right Round 1 Game 8 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_right_r2_g1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_r2_g1_id', to='basketball.Team', verbose_name='Bottom Right Round 2 Game 1 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_right_r2_g2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_r2_g2_id', to='basketball.Team', verbose_name='Bottom Right Round 2 Game 2 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_right_r2_g3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_r2_g3_id', to='basketball.Team', verbose_name='Bottom Right Round 2 Game 3 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_right_r2_g4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_r2_g4_id', to='basketball.Team', verbose_name='Bottom Right Round 2 Game 4 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_right_ss_g1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_ss_g1_id', to='basketball.Team', verbose_name='Bottom Right Sweet 16 Game 1 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='bottom_right_ss_g2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_ss_g2_id', to='basketball.Team', verbose_name='Bottom Right Sweet 16 Game 2 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='championship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='championship_id', to='basketball.Team', verbose_name='National Champion'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='ff_left',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ff_left_id', to='basketball.Team', verbose_name='Left Final Four Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='ff_right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ff_right_id', to='basketball.Team', verbose_name='Right Final Four Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(192)]),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_left_ee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_ee_id', to='basketball.Team', verbose_name='Top Left Elite Eight Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_left_r1_g1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_r1_g1_id', to='basketball.Team', verbose_name='Top Left Round 1 Game 1 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_left_r1_g2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_r1_g2_id', to='basketball.Team', verbose_name='Top Left Round 1 Game 2 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_left_r1_g3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_r1_g3_id', to='basketball.Team', verbose_name='Top Left Round 1 Game 3 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_left_r1_g4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_r1_g4_id', to='basketball.Team', verbose_name='Top Left Round 1 Game 4 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_left_r1_g5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_r1_g5_id', to='basketball.Team', verbose_name='Top Left Round 1 Game 5 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_left_r1_g6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_r1_g6_id', to='basketball.Team', verbose_name='Top Left Round 1 Game 6 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_left_r1_g7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_r1_g7_id', to='basketball.Team', verbose_name='Top Left Round 1 Game 7 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_left_r1_g8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_r1_g8_id', to='basketball.Team', verbose_name='Top Left Round 1 Game 8 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_left_r2_g1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_r2_g1_id', to='basketball.Team', verbose_name='Top Left Round 2 Game 1 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_left_r2_g2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_r2_g2_id', to='basketball.Team', verbose_name='Top Left Round 2 Game 2 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_left_r2_g3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_r2_g3_id', to='basketball.Team', verbose_name='Top Left Round 2 Game 3 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_left_r2_g4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_r2_g4_id', to='basketball.Team', verbose_name='Top Left Round 2 Game 4 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_left_ss_g1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_ss_g1_id', to='basketball.Team', verbose_name='Top Left Sweet 16 Game 1 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_left_ss_g2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_ss_g2_id', to='basketball.Team', verbose_name='Top Left Sweet 16 Game 2 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_right_ee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_ee_id', to='basketball.Team', verbose_name='Top Right Elite Eight Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_right_r1_g1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_r1_g1_id', to='basketball.Team', verbose_name='Top Right Round 1 Game 1 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_right_r1_g2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_r1_g2_id', to='basketball.Team', verbose_name='Top Right Round 1 Game 2 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_right_r1_g3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_r1_g3_id', to='basketball.Team', verbose_name='Top Right Round 1 Game 3 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_right_r1_g4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_r1_g4_id', to='basketball.Team', verbose_name='Top Right Round 1 Game 4 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_right_r1_g5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_r1_g5_id', to='basketball.Team', verbose_name='Top Right Round 1 Game 5 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_right_r1_g6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_r1_g6_id', to='basketball.Team', verbose_name='Top Right Round 1 Game 6 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_right_r1_g7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_r1_g7_id', to='basketball.Team', verbose_name='Top Right Round 1 Game 7 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_right_r1_g8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_r1_g8_id', to='basketball.Team', verbose_name='Top Right Round 1 Game 8 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_right_r2_g1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_r2_g1_id', to='basketball.Team', verbose_name='Top Right Round 2 Game 1 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_right_r2_g2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_r2_g2_id', to='basketball.Team', verbose_name='Top Right Round 2 Game 2 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_right_r2_g3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_r2_g3_id', to='basketball.Team', verbose_name='Top Right Round 2 Game 3 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_right_r2_g4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_r2_g4_id', to='basketball.Team', verbose_name='Top Right Round 2 Game 4 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_right_ss_g1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_ss_g1_id', to='basketball.Team', verbose_name='Top Right Sweet 16 Game 1 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='top_right_ss_g2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_ss_g2_id', to='basketball.Team', verbose_name='Top Right Sweet 16 Game 2 Winner'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='year',
            field=models.PositiveSmallIntegerField(default=2018, validators=[django.core.validators.MinValueValidator(1939), django.core.validators.MaxValueValidator(2018)]),
        ),
    ]
