# Generated by Django 2.0.9 on 2018-12-13 23:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0036_auto_20181213_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='bottom_left_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_1_id', to='basketball.Team', verbose_name='Bottom Left 1 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_left_10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_10_id', to='basketball.Team', verbose_name='Bottom Left 10 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_left_11',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_11_id', to='basketball.Team', verbose_name='Bottom Left 11 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_left_12',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_12_id', to='basketball.Team', verbose_name='Bottom Left 12 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_left_13',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_13_id', to='basketball.Team', verbose_name='Bottom Left 13 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_left_14',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_14_id', to='basketball.Team', verbose_name='Bottom Left 14 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_left_15',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_15_id', to='basketball.Team', verbose_name='Bottom Left 15 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_left_16',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_16_id', to='basketball.Team', verbose_name='Bottom Left 16 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_left_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_2_id', to='basketball.Team', verbose_name='Bottom Left 2 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_left_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_3_id', to='basketball.Team', verbose_name='Bottom Left 3 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_left_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_4_id', to='basketball.Team', verbose_name='Bottom Left 4 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_left_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_5_id', to='basketball.Team', verbose_name='Bottom Left 5 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_left_6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_6_id', to='basketball.Team', verbose_name='Bottom Left 6 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_left_7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_7_id', to='basketball.Team', verbose_name='Bottom Left 7 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_left_8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_8_id', to='basketball.Team', verbose_name='Bottom Left 8 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_left_9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_left_9_id', to='basketball.Team', verbose_name='Bottom Left 9 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_left_region',
            field=models.CharField(choices=[('EAST', 'East'), ('MIDWEST', 'Midwest'), ('SOUTH', 'South'), ('SOUTHEAST', 'Southeast'), ('SOUTHWEST', 'Southwest'), ('WEST', 'West')], max_length=10, verbose_name='Bottom Left Region Name'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_right_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_1_id', to='basketball.Team', verbose_name='Bottom Right 1 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_right_10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_10_id', to='basketball.Team', verbose_name='Bottom Right 10 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_right_11',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_11_id', to='basketball.Team', verbose_name='Bottom Right 11 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_right_12',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_12_id', to='basketball.Team', verbose_name='Bottom Right 12 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_right_13',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_13_id', to='basketball.Team', verbose_name='Bottom Right 13 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_right_14',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_14_id', to='basketball.Team', verbose_name='Bottom Right 14 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_right_15',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_15_id', to='basketball.Team', verbose_name='Bottom Right 15 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_right_16',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_16_id', to='basketball.Team', verbose_name='Bottom Right 16 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_right_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_2_id', to='basketball.Team', verbose_name='Bottom Right 2 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_right_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_3_id', to='basketball.Team', verbose_name='Bottom Right 3 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_right_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_4_id', to='basketball.Team', verbose_name='Bottom Right 4 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_right_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_5_id', to='basketball.Team', verbose_name='Bottom Right 5 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_right_6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_6_id', to='basketball.Team', verbose_name='Bottom Right 6 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_right_7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_7_id', to='basketball.Team', verbose_name='Bottom Right 7 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_right_8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_8_id', to='basketball.Team', verbose_name='Bottom Right 8 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_right_9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_right_9_id', to='basketball.Team', verbose_name='Bottom Right 9 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bottom_right_region',
            field=models.CharField(choices=[('EAST', 'East'), ('MIDWEST', 'Midwest'), ('SOUTH', 'South'), ('SOUTHEAST', 'Southeast'), ('SOUTHWEST', 'Southwest'), ('WEST', 'West')], max_length=10, verbose_name='Bottom Right Region Name'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_left_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_1_id', to='basketball.Team', verbose_name='Top Left 1 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_left_10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_10_id', to='basketball.Team', verbose_name='Top Left 10 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_left_11',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_11_id', to='basketball.Team', verbose_name='Top Left 11 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_left_12',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_12_id', to='basketball.Team', verbose_name='Top Left 12 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_left_13',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_13_id', to='basketball.Team', verbose_name='Top Left 13 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_left_14',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_14_id', to='basketball.Team', verbose_name='Top Left 14 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_left_15',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_15_id', to='basketball.Team', verbose_name='Top Left 15 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_left_16',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_16_id', to='basketball.Team', verbose_name='Top Left 16 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_left_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_2_id', to='basketball.Team', verbose_name='Top Left 2 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_left_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_3_id', to='basketball.Team', verbose_name='Top Left 3 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_left_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_4_id', to='basketball.Team', verbose_name='Top Left 4 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_left_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_5_id', to='basketball.Team', verbose_name='Top Left 5 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_left_6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_6_id', to='basketball.Team', verbose_name='Top Left 6 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_left_7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_7_id', to='basketball.Team', verbose_name='Top Left 7 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_left_8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_8_id', to='basketball.Team', verbose_name='Top Left 8 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_left_9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_left_9_id', to='basketball.Team', verbose_name='Top Left 9 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_left_region',
            field=models.CharField(choices=[('EAST', 'East'), ('MIDWEST', 'Midwest'), ('SOUTH', 'South'), ('SOUTHEAST', 'Southeast'), ('SOUTHWEST', 'Southwest'), ('WEST', 'West')], max_length=10, verbose_name='Top Left Region Name'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_right_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_1_id', to='basketball.Team', verbose_name='Top Right 1 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_right_10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_10_id', to='basketball.Team', verbose_name='Top Right 10 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_right_11',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_11_id', to='basketball.Team', verbose_name='Top Right 11 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_right_12',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_12_id', to='basketball.Team', verbose_name='Top Right 12 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_right_13',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_13_id', to='basketball.Team', verbose_name='Top Right 13 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_right_14',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_14_id', to='basketball.Team', verbose_name='Top Right 14 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_right_15',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_15_id', to='basketball.Team', verbose_name='Top Right 15 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_right_16',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_16_id', to='basketball.Team', verbose_name='Top Right 16 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_right_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_2_id', to='basketball.Team', verbose_name='Top Right 2 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_right_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_3_id', to='basketball.Team', verbose_name='Top Right 3 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_right_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_4_id', to='basketball.Team', verbose_name='Top Right 4 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_right_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_5_id', to='basketball.Team', verbose_name='Top Right 5 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_right_6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_6_id', to='basketball.Team', verbose_name='Top Right 6 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_right_7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_7_id', to='basketball.Team', verbose_name='Top Right 7 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_right_8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_8_id', to='basketball.Team', verbose_name='Top Right 8 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_right_9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_right_9_id', to='basketball.Team', verbose_name='Top Right 9 Seed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_right_region',
            field=models.CharField(choices=[('EAST', 'East'), ('MIDWEST', 'Midwest'), ('SOUTH', 'South'), ('SOUTHEAST', 'Southeast'), ('SOUTHWEST', 'Southwest'), ('WEST', 'West')], max_length=10, verbose_name='Top Right Region Name'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='year',
            field=models.PositiveSmallIntegerField(default=2018, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1939), django.core.validators.MaxValueValidator(2018)]),
        ),
    ]
