# Generated by Django 2.0.9 on 2019-01-05 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0038_auto_20181213_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season_stats',
            options={},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
        migrations.AlterField(
            model_name='bracket',
            name='year',
            field=models.PositiveSmallIntegerField(default=2019, validators=[django.core.validators.MinValueValidator(1939)]),
        ),
        migrations.AlterField(
            model_name='season_stats',
            name='year',
            field=models.PositiveSmallIntegerField(default=2019, validators=[django.core.validators.MinValueValidator(1939)]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='year',
            field=models.PositiveSmallIntegerField(default=2019, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1939)]),
        ),
    ]
