# Generated by Django 2.0.10 on 2019-01-18 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0039_auto_20190105_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MOM', 'Mom'), ('AUNT', 'Aunt'), ('ME', 'Me')], max_length=10)),
                ('first_place', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('second_place', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('third_place', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('correct_champions', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('average_predicted_upsets', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('average_correct_upsets', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
