# Generated by Django 2.0.9 on 2019-01-05 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
    ]
