# Generated by Django 2.0.9 on 2019-01-05 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0002_delete_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('all_cohort', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('mam_cohort', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('mas_cohort', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('mbl_cohort', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('mhi_cohort', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('mtr_cohort', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('mwh_cohort', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cwd_cohort', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ecd_cohort', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('lep_cohort', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('num_schools', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
