# Generated by Django 2.0.9 on 2019-01-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
    ]
