# Generated by Django 2.0.9 on 2019-01-07 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0006_delete_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('all_cohort', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('mam_cohort', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('mas_cohort', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('mbl_cohort', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('mhi_cohort', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('mtr_cohort', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('mwh_cohort', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cwd_cohort', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ecd_cohort', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('lep_cohort', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('num_schools', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('all_rate', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('mam_rate', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('mas_rate', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('mbl_rate', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('mhi_rate', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('mtr_rate', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('mwh_rate', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('cwd_rate', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('ecd_rate', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('lep_rate', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ],
        ),
    ]
